### ISSUE TITLE
Pages of matches with game_id

### ISSUE THREAD

**Issue by s4mukka** [rivalrygg/rivalry-api#10]
When I make a request passing the 'page' and the 'game_id' in '/api/v1/matches' it always returns the first page.

Example:
https://www.rivalry.com/api/v1/matches?page=2&game_id=5 // return first page
https://www.rivalry.com/api/v1/matches?page=3&game_id=5 // return first page

**Comment by s4mukka** [comment]
<br class="Apple-interchange-newline">@d1am0nd&nbsp;@ryantology&nbsp;@kjunggithub&nbsp;@davidgrzyb

**Comment by atpearl** [comment]
This issue has been resolved. The correct data is now being returned for each page.
