### ISSUE TITLE
[Doubt] Is the Rivalry API still active?

### ISSUE THREAD

**Issue by rafaelcamaram** [rivalrygg/rivalry-api#9]
Hey, how are you? 

I would like to know if this API is still active. I meant, if it's still returning valid data; since the last commit was in October 2019.

Thank you!

**Comment by rafaelcamaram** [comment]
@d1am0nd @ryantology @kjunggithub @davidgrzyb

**Comment by ryantology** [comment]
Yes, the API is still active. If you have any issues please feel free to submit issues.
Plugging in the URL in browser is the first step. https://app.rivalry.com/api/v1/matches

We will be making some change in the near future so we would suggest watching the repo for changes.
